### ISSUE TITLE
Line formatting Error

### ISSUE THREAD

**Issue by ultrons** [google-coral/test_data#1]
It looks like:
https://github.com/c-ai/edgetpuvision/blob/cfd66416cb5d60827a2f0e318a47f98529378f91/edgetpuvision/utils.py#L6
Is expecting linenumber to be printed in every line, something like:
https://github.com/ultrons/test_data/blob/coral/imagenet_labels.txt

unsure of dependencies/consequences of touching either.
But something needs to be fixed else I get an error saying group called on None object.
When executing image classification demo from:
https://coral.ai/docs/dev-board/camera/#run-a-demo-with-the-camera

**Comment by hjonnala** [comment]
can you please share the command you are executing and the error.

**Comment by dmitriykovalev** [comment]
We don't have explicit line numbers in label files (that's a recent change). You are referring to the [old fork](https://github.com/c-ai/edgetpuvision/blob/cfd66416cb5d60827a2f0e318a47f98529378f91/edgetpuvision/utils.py#L6) of `edgetpuvision` which we have no relation to. Please check the https://coral.googlesource.com/edgetpuvision/ for the latest correct code. You may use [read_label_file](https://github.com/google-coral/pycoral/blob/master/pycoral/utils/dataset.py#L20) function, which supports both old and new formats, to read label file.

**Comment by GokulSudheesh** [comment]
Kind request to mention this in the documentation as well.
https://coral.ai/docs/dev-board/camera/#download-the-model-files

**Comment by abliss** [comment]
I also got this error while following the instructions on https://coral.ai/docs/dev-board-mini/camera/#run-a-classification-model . Did the authors of that page not check in with you before embedding a deep link to a file on your master branch?

Specifically, running 
```
edgetpu_classify \
--model ${DEMO_FILES}/mobilenet_v2_1.0_224_quant_edgetpu.tflite \
--labels ${DEMO_FILES}/imagenet_labels.txt
```
fails with
```
Traceback (most recent call last):
  File "/usr/bin/edgetpu_classify", line 11, in <module>
    load_entry_point('edgetpuvision==7.0', 'console_scripts', 'edgetpu_classify')()
  File "/usr/lib/python3/dist-packages/edgetpuvision/classify.py", line 171, in main                                                                                      run_app(add_render_gen_args, render_gen)
  File "/usr/lib/python3/dist-packages/edgetpuvision/apps.py", line 70, in run_app
    display=args.displaymode):
  File "/usr/lib/python3/dist-packages/edgetpuvision/gstreamer.py", line 246, in run_gen
    inference_size = render_overlay_gen.send(None)  # Initialize.                                                                                                       File "/usr/lib/python3/dist-packages/edgetpuvision/classify.py", line 120, in render_gen
    labels = utils.load_labels(args.labels)
  File "/usr/lib/python3/dist-packages/edgetpuvision/utils.py", line 28, in load_labels
    return {int(num): text.strip() for num, text in lines}
  File "/usr/lib/python3/dist-packages/edgetpuvision/utils.py", line 28, in <dictcomp>
    return {int(num): text.strip() for num, text in lines}
  File "/usr/lib/python3/dist-packages/edgetpuvision/utils.py", line 27, in <genexpr>
    lines = (LABEL_PATTERN.match(line).groups() for line in f.readlines())
AttributeError: 'NoneType' object has no attribute 'groups'
```

**Comment by adrianfn21** [comment]
@abliss Same problem here.

I was able to surpass it following the steps for the Dev Board (same steps, different link for image labels). Here it is: https://coral.ai/docs/dev-board/camera/#download-the-model-files

Hope this can help you!
