### ISSUE TITLE
Coral TPU Models

### ISSUE THREAD

**Issue by jcastro** [google-coral/test_data#4]
Hello,
I'm currently using a Coral TPU (USB) with Frigate, which uses Tensorflow which uses https://github.com/google-coral/test_data/raw/master/ssdlite_mobiledet_coco_qat_postprocess_edgetpu.tflite model for different object recognition.

I noticed the person recognition is nice, but sometimes fails (for example recognises a chair with a jacket as a person, or a bottle of water as a person.

I was wondering if there's updated models or better suited models specifically for person recognition?. Also, are the models available on this repo updated regularly to improve recognition?

Thanks!

**Comment by hjonnala** [comment]
@jcastro please check [project-bodypix](https://github.com/google-coral/project-bodypix) and [project-posent](https://github.com/google-coral/project-posenet) for person recognition models.

This models won't be updated regularly. But definitely, whenever some improvements are changes have been made to the models.

**Comment by jcastro** [comment]
thank you!
